using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace AutoValidate
{
    [Generator]
    public sealed class AutoValidateGenerator : IIncrementalGenerator
    {
        // ── Attribute source ────────────────────────────────────────────────────
        private const string AttributeSource = @"// <auto-generated/>
#nullable enable
using System;

namespace AutoValidate
{
    /// <summary>DI lifetime for a registered validator.</summary>
    public enum ValidatorLifetime { Scoped = 0, Singleton = 1, Transient = 2 }

    /// <summary>Excludes this validator from auto-registration.</summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class SkipValidatorAttribute : Attribute { }

    /// <summary>Overrides the DI lifetime for this validator. Default is Scoped.</summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class ValidatorLifetimeAttribute : Attribute
    {
        public ValidatorLifetime Lifetime { get; }
        public ValidatorLifetimeAttribute(ValidatorLifetime lifetime = ValidatorLifetime.Scoped)
            => Lifetime = lifetime;
    }

    /// <summary>Registers a hosted service that validates an instance of the model at application startup.</summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class ValidateOnStartupAttribute : Attribute { }
}
";

        // ── Diagnostics ─────────────────────────────────────────────────────────
        private static readonly DiagnosticDescriptor AV001_DuplicateValidator = new(
            id: "AV001",
            title: "Duplicate validator",
            messageFormat: "Multiple validators found for '{0}': {1}. Only the first will be registered.",
            category: "AutoValidate",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "Each model type should have at most one validator registered.");

        private static readonly DiagnosticDescriptor AV002_AttributeOnNonValidator = new(
            id: "AV002",
            title: "AutoValidate attribute on non-validator class",
            messageFormat: "'{0}' has [{1}] but does not inherit AbstractValidator<T>. The attribute will be ignored.",
            category: "AutoValidate",
            defaultSeverity: DiagnosticSeverity.Warning,
            isEnabledByDefault: true,
            description: "AutoValidate attributes should only be applied to classes that inherit AbstractValidator<T>.");

        // ── Data models ─────────────────────────────────────────────────────────
        private enum ValidatorLifetime { Scoped, Singleton, Transient }

        private sealed class ValidatorInfo
        {
            public string ValidatorFullName { get; set; } = "";
            public string ModelFullName { get; set; } = "";
            public ValidatorLifetime Lifetime { get; set; } = ValidatorLifetime.Scoped;
            public bool ValidateOnStartup { get; set; }
        }

        // ── IIncrementalGenerator ───────────────────────────────────────────────
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Always emit the attribute types
            context.RegisterPostInitializationOutput(ctx =>
                ctx.AddSource("AutoValidate.Attributes.g.cs", AttributeSource));

            // Find candidate class declarations (those with a base list)
            var candidates = context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is TypeDeclarationSyntax { BaseList: { } },
                transform: TransformCandidate)
                .Where(x => x is not null)
                .Select((x, _) => x!);

            var diagnostics = candidates
                .Where(x => x.ValidatorFullName == "" || x.ModelFullName == "")
                .Select((_, _) => (object?)null); // placeholder — diagnostics emitted in transform

            var validValidators = candidates
                .Where(x => x.ValidatorFullName != "" && x.ModelFullName != "")
                .Collect();

            context.RegisterSourceOutput(validValidators, GenerateSource);
        }

        // ── Transform ───────────────────────────────────────────────────────────
        private static ValidatorInfo? TransformCandidate(
            GeneratorSyntaxContext ctx, CancellationToken ct)
        {
            var typeSyntax = (TypeDeclarationSyntax)ctx.Node;
            if (ctx.SemanticModel.GetDeclaredSymbol(typeSyntax, ct) is not INamedTypeSymbol typeSymbol)
                return null;

            bool hasSkip = HasAttribute(typeSymbol, "AutoValidate.SkipValidatorAttribute");
            bool hasLifetime = HasAttribute(typeSymbol, "AutoValidate.ValidatorLifetimeAttribute");
            bool hasStartup = HasAttribute(typeSymbol, "AutoValidate.ValidateOnStartupAttribute");

            // Check if it's an AbstractValidator<T>
            ITypeSymbol? modelType = GetAbstractValidatorTypeArg(typeSymbol);

            // Report attribute-on-non-validator (we can't emit diagnostics from transform — skip for now)
            if (modelType is null)
                return null; // Not a validator — ignore (attributes without inheritance are handled separately)

            // Skip abstract validators — they can't be instantiated
            if (typeSymbol.IsAbstract)
                return null;

            if (hasSkip)
                return null; // Opted out

            var lifetime = ValidatorLifetime.Scoped;
            if (hasLifetime)
            {
                var attr = typeSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == "AutoValidate.ValidatorLifetimeAttribute");
                if (attr?.ConstructorArguments.Length > 0 &&
                    attr.ConstructorArguments[0].Value is int lifetimeInt)
                {
                    lifetime = lifetimeInt switch
                    {
                        0 => ValidatorLifetime.Scoped,
                        1 => ValidatorLifetime.Singleton,
                        2 => ValidatorLifetime.Transient,
                        _ => ValidatorLifetime.Scoped
                    };
                }
            }

            return new ValidatorInfo
            {
                ValidatorFullName = typeSymbol.ToDisplayString(),
                ModelFullName = modelType.ToDisplayString(),
                Lifetime = lifetime,
                ValidateOnStartup = hasStartup
            };
        }

        // ── Source generation ───────────────────────────────────────────────────
        private static void GenerateSource(
            SourceProductionContext ctx,
            ImmutableArray<ValidatorInfo> validators)
        {
            if (validators.IsDefaultOrEmpty) return;

            // Detect duplicates
            var byModel = new Dictionary<string, List<ValidatorInfo>>();
            foreach (var v in validators)
            {
                if (!byModel.TryGetValue(v.ModelFullName, out var list))
                {
                    list = new List<ValidatorInfo>();
                    byModel[v.ModelFullName] = list;
                }
                list.Add(v);
            }

            // Emit duplicate warnings (use first occurrence)
            var deduped = new List<ValidatorInfo>();
            foreach (var kv in byModel)
            {
                if (kv.Value.Count > 1)
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(
                        AV001_DuplicateValidator,
                        Location.None,
                        kv.Key,
                        string.Join(", ", kv.Value.Select(v => v.ValidatorFullName))));
                }
                deduped.Add(kv.Value[0]);
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using FluentValidation;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using Microsoft.Extensions.Hosting;");
            sb.AppendLine("using Microsoft.AspNetCore.Http;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine("namespace AutoValidate");
            sb.AppendLine("{");

            // ── AddValidators() extension ────────────────────────────────────
            sb.AppendLine("    public static partial class ValidatorExtensions");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>Registers all discovered validators with the DI container.</summary>");
            sb.AppendLine("        public static IServiceCollection AddValidators(this IServiceCollection services)");
            sb.AppendLine("        {");

            foreach (var v in deduped)
            {
                string register = v.Lifetime switch
                {
                    ValidatorLifetime.Singleton => "AddSingleton",
                    ValidatorLifetime.Transient  => "AddTransient",
                    _                            => "AddScoped"
                };
                sb.AppendLine($"            services.{register}<IValidator<{v.ModelFullName}>, {v.ValidatorFullName}>();");

                if (v.ValidateOnStartup)
                    sb.AppendLine($"            services.AddHostedService<ValidatorStartupService<{v.ModelFullName}>>();");
            }

            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // ── WithValidation<T>() Minimal API helper ───────────────────────
            sb.AppendLine("#if NET7_0_OR_GREATER");
            sb.AppendLine("        /// <summary>Adds a validation endpoint filter for the given model type.</summary>");
            sb.AppendLine("        public static RouteHandlerBuilder WithValidation<T>(");
            sb.AppendLine("            this RouteHandlerBuilder builder) where T : class");
            sb.AppendLine("            => builder.AddEndpointFilter<ValidationFilter<T>>();");
            sb.AppendLine("#endif");
            sb.AppendLine("    }");

            // ── ValidationFilter<T> ──────────────────────────────────────────
            sb.AppendLine();
            sb.AppendLine("#if NET7_0_OR_GREATER");
            sb.AppendLine("    internal sealed class ValidationFilter<T> : IEndpointFilter where T : class");
            sb.AppendLine("    {");
            sb.AppendLine("        private readonly IValidator<T> _validator;");
            sb.AppendLine("        public ValidationFilter(IValidator<T> validator) => _validator = validator;");
            sb.AppendLine();
            sb.AppendLine("        public async ValueTask<object?> InvokeAsync(");
            sb.AppendLine("            EndpointFilterInvocationContext context,");
            sb.AppendLine("            EndpointFilterDelegate next)");
            sb.AppendLine("        {");
            sb.AppendLine("            var model = context.Arguments.OfType<T>().FirstOrDefault();");
            sb.AppendLine("            if (model is not null)");
            sb.AppendLine("            {");
            sb.AppendLine("                var result = await _validator.ValidateAsync(model);");
            sb.AppendLine("                if (!result.IsValid)");
            sb.AppendLine("                    return Results.ValidationProblem(result.ToDictionary());");
            sb.AppendLine("            }");
            sb.AppendLine("            return await next(context);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("#endif");

            // ── ValidatorStartupService<T> ───────────────────────────────────
            bool anyStartup = deduped.Any(v => v.ValidateOnStartup);
            if (anyStartup)
            {
                sb.AppendLine();
                sb.AppendLine("    /// <summary>Hosted service that validates a model instance at application startup.</summary>");
                sb.AppendLine("    internal sealed class ValidatorStartupService<T> : IHostedService where T : class");
                sb.AppendLine("    {");
                sb.AppendLine("        private readonly IServiceProvider _services;");
                sb.AppendLine("        public ValidatorStartupService(IServiceProvider services) => _services = services;");
                sb.AppendLine();
                sb.AppendLine("        public async Task StartAsync(CancellationToken cancellationToken)");
                sb.AppendLine("        {");
                sb.AppendLine("            using var scope = _services.CreateScope();");
                sb.AppendLine("            var validator = scope.ServiceProvider.GetRequiredService<IValidator<T>>();");
                sb.AppendLine("            var instance = scope.ServiceProvider.GetService<T>();");
                sb.AppendLine("            if (instance is null) return;");
                sb.AppendLine("            var result = await validator.ValidateAsync(instance, cancellationToken);");
                sb.AppendLine("            if (!result.IsValid)");
                sb.AppendLine("            {");
                sb.AppendLine("                var errors = string.Join(\", \", System.Linq.Enumerable.Select(result.Errors, e => e.ErrorMessage));");
                sb.AppendLine("                throw new InvalidOperationException(");
                sb.AppendLine($"                    $\"Startup validation failed for {{typeof(T).Name}}: {{errors}}\");");
                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine("        public Task StopAsync(CancellationToken cancellationToken) => Task.CompletedTask;");
                sb.AppendLine("    }");
            }

            sb.AppendLine("}");

            ctx.AddSource("AutoValidate.g.cs", sb.ToString());
        }

        // ── Helpers ─────────────────────────────────────────────────────────────
        private static ITypeSymbol? GetAbstractValidatorTypeArg(INamedTypeSymbol typeSymbol)
        {
            INamedTypeSymbol? current = typeSymbol.BaseType;
            while (current is not null)
            {
                if (current.OriginalDefinition.ToDisplayString() == "FluentValidation.AbstractValidator<T>")
                    return current.TypeArguments.Length > 0 ? current.TypeArguments[0] : null;
                current = current.BaseType;
            }
            return null;
        }

        private static bool HasAttribute(INamedTypeSymbol symbol, string fullyQualifiedName)
            => symbol.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == fullyQualifiedName);
    }
}
